site_name: 'MESQUAL Suite Documentation'
site_url: 'https://docs.mesqual.io/'
repo_url: 'https://github.com/helgeesch/mesqual-vanilla-studies/'


theme:
  name: material
  logo: assets/logo-white.svg
  palette:
    primary: 'teal'
    accent: 'amber'
  features:
    - navigation.tabs
    - content.tabs.link
    - navigation.sections

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 5
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: ['.']
      check_paths: true

plugins:
  - search
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [submodules/mesqual]
          options:
            heading_level: 2
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            show_root_members_full_path: false
            show_symbol_type_heading: true
            show_category_heading: false
            show_root_toc_entry: false
            signature_crossrefs: true
            show_signature_annotations: true
            show_signature_type_parameters: true
            members_order: source
            modernize_annotations: true
            separate_signature: true
            merge_init_into_class: false
  - monorepo
  - mkdocs-jupyter:
      include_source: True
      allow_errors: False
      kernel_name: python3
      ignore:
        - "*.py"

#exclude_docs: |

nav:
  - Home:
    - index.md
    - About MESQUAL Framework: about_mesqual.md
    - About Vanilla Studies Repository: about_vanilla_studies.md
  - MESQUAL API Reference: '!include submodules/mesqual/mkdocs.yml'
  #  - MESQUAL PYPSA: '!include submodules/mesqual-pypsa/mkdocs.yml'
  #  - MESQUAL AI: '!include submodules/mesqual-ai/mkdocs.yml'
  - Studies & Examples:
      - Intro to MESQUAL: '!include studies/mkdocs_study_01.yml'
      - PyPSA EUR Example: '!include studies/mkdocs_study_02.yml'
      - Plexos Example: '!include studies/mkdocs_study_03.yml'
